name: wavenet
description: A simple wrapper for accessing Google's Text-To-Spech API and converting the results to MP3 files.
version: 2.0.6
homepage: https://github.com/jonafeucht/Flutter-WaveNet-API
repository: https://github.com/jonafeucht/Flutter-WaveNet-API

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ">=2.0.11 <=3.0.0"

dev_dependencies:
  test: ">=1.22.1 <=2.0.0"

flutter:

false_secrets:
  - example/lib/main.dart
